### ISSUE TITLE
TypeError: shim.js - Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"

### ISSUE THREAD

**Issue by thegitparticle** [tradle/react-native-crypto#65]
I installed react-native-crypto and others needed as said. While trying to build for iOS, I get this error and the build fails.

`error shim.js: /Users/Desktop/appfolder/shim.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral".
TypeError: /Users/Desktop/appfolder/shim.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"
    at Object.validate (/Users/san/Desktop/soupapp/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/Users/san/Desktop/soupapp/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/Users/san/Desktop/soupapp/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/Users/san/Desktop/soupapp/node_modules/@babel/traverse/lib/path/replacement.js:170:5)
    at NodePath.replaceWith (/Users/san/Desktop/soupapp/node_modules/@babel/traverse/lib/path/replacement.js:152:8)
    at PluginPass.MemberExpression (/Users/san/Desktop/soupapp/node_modules/react-native-dotenv/index.js:122:16)
    at newFn (/Users/san/Desktop/soupapp/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/san/Desktop/soupapp/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/san/Desktop/soupapp/node_modules/@babel/traverse/lib/path/context.js:40:17)
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code
`

I tried clearing caches, builds, derived data, and all, still to no avail. Any help?

**Comment by Baskerville42** [comment]
Try this solution
https://github.com/facebook/react-native/issues/7607#issuecomment-376483751
